# Generated by Django 5.0b1 on 2024-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_code', models.CharField(max_length=150, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام دانشجو')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی دانشجو')),
                ('birthday_date', models.DateField(verbose_name='تاریخ تولد دانشجو')),
                ('telephone', models.CharField(max_length=150, verbose_name='شماره تلفن ثابت دانشجو')),
                ('mobile', models.CharField(max_length=150, verbose_name='شماره تلفن همراه دانشجو')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل دانشجو')),
                ('score', models.IntegerField(verbose_name='نمره دانشجو')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت دانشجو')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
