# Generated by Django 5.0b1 on 2024-03-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='نام مقطع')),
                ('regdate', models.DateField(null=True, verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام ترم')),
                ('startDate', models.DateField(verbose_name='تاریخ شروع')),
                ('endDate', models.DateField(verbose_name='تاریخ پایان')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام درس')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.level', verbose_name='مقطع')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.course', verbose_name='درس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.student', verbose_name='دانشجو')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.term', verbose_name='ترم')),
            ],
        ),
    ]
