# Generated by Django 5.0.4 on 2024-04-24 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeOfEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Name of degree')),
                ('study', models.TextField(max_length=200, verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'مدرک تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='نام ترم')),
                ('regdate', models.DateField(null=True, verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مقطع',
                'verbose_name_plural': 'مقطع ها',
                'ordering': ['regdate'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام ترم')),
                ('startDate', models.DateField(verbose_name='تاریخ شروع')),
                ('endDate', models.DateField(verbose_name='تاریخ پایان')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ترم',
                'verbose_name_plural': 'ترم ها',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_code', models.CharField(max_length=10, verbose_name='کد ملی دانشجو')),
                ('birthday_date', models.DateField(verbose_name='تاریخ تولد')),
                ('telephone', models.CharField(max_length=11, verbose_name='شماره ثابت')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^09\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='شماره موبایل')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجوها',
                'ordering': ['user__first_name', 'regdate'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_code', models.CharField(max_length=10, verbose_name='کدم ملی استاد')),
                ('birthday_date', models.DateField(verbose_name='تاریخ تولد')),
                ('telephone', models.CharField(max_length=11, verbose_name='شماره ثابت')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.degreeofeducation', verbose_name='مدرک تحصیلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'استادها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام درس')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.level', verbose_name='مقطع')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rest_api.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='StudentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.course', verbose_name='درس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.student', verbose_name='دانشجو')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.term', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'ترم دانشجو',
                'verbose_name_plural': 'ترم دانشجو ها',
            },
        ),
    ]
