# Generated by Django 5.0.4 on 2024-04-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Section name')),
                ('regdate', models.DateField(null=True, verbose_name='Date of Registration')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['regdate'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_code', models.CharField(max_length=150, verbose_name="Student's national code")),
                ('first_name', models.CharField(max_length=150, verbose_name="ّStudent's name")),
                ('last_name', models.CharField(max_length=150, verbose_name="Student's last name")),
                ('birthday_date', models.DateField(verbose_name='Date of birth')),
                ('telephone', models.CharField(max_length=150, verbose_name='landline number')),
                ('mobile', models.CharField(max_length=150, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('regdate', models.DateField(verbose_name='Date of Registration')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['first_name', 'regdate'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_code', models.CharField(max_length=150, verbose_name="Teacher's national code")),
                ('first_name', models.CharField(max_length=150, verbose_name="Teacher's name")),
                ('last_name', models.CharField(max_length=150, verbose_name="Teacher's last name")),
                ('birthday_date', models.DateField(verbose_name='Date of birth')),
                ('telephone', models.CharField(max_length=150, verbose_name='landline number')),
                ('mobile', models.CharField(max_length=150, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('field', models.CharField(max_length=150, verbose_name='Field of Study')),
                ('regdate', models.DateField(verbose_name='Date of Registration')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Term name')),
                ('startDate', models.DateField(verbose_name='Start date')),
                ('endDate', models.DateField(verbose_name='End date')),
                ('regdate', models.DateField(verbose_name='Date of Registration')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of Course')),
                ('regdate', models.DateField(verbose_name='Date of Registration')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.level', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='StudentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate', models.DateField(verbose_name='Date of Registration')),
                ('description', models.TextField(verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.student', verbose_name='Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Student Term',
                'verbose_name_plural': 'Student Terms',
            },
        ),
    ]
