# Generated by Django 5.0b1 on 2024-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_code', models.CharField(max_length=150, verbose_name='کد ملی استاد')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام استاد')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی استاد')),
                ('birthday_date', models.DateField(verbose_name='تاریخ تولد استاد')),
                ('telephone', models.CharField(max_length=150, verbose_name='شماره تلفن ثابت استاد')),
                ('mobile', models.CharField(max_length=150, verbose_name='شماره تلفن استاد')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل استاد')),
                ('field', models.CharField(max_length=150, verbose_name='رشته تحصیلی استاد')),
                ('regdate', models.DateField(verbose_name='تاریخ ثبت استاد')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
